devsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('prmonde.urls')),
]

prmonde/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^order/$', views.order, name='order'),
    url(r'^requirements/$', views.requirements, name='requirements'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^articles/$', views.articles, name='articles'),
    url(r'^articles/(?P<pk>[0-9]+)/$', views.article_item, name='article_item'),
    url(r'^success/$', views.form_success, name='form_success'),
]

prmonde/models.py
from django.db import models
from django.utils import timezone

class Article(models.Model):
	title = models.CharField(max_length=250)
	preview = models.TextField()
	content = models.TextField()
	date = models.DateTimeField(default=timezone.now)
	source = models.CharField(max_length=500)

	def publish(self):
		self.date = timezone.now()
		self.save()

	def __str__(self):
		return self.title

prmonde/forms.py
from django import forms

class OrderForm(forms.Form):
	PUBLICITY=[('transport','tr_lable'),('presse','pr_lable')]
	company=forms.CharField(max_length=100)
	product=forms.CharField(max_length=200)
	design=forms.BooleanField(required=False)
	publicity_type=forms.ChoiceField(choices=PUBLICITY, widget=forms.RadioSelect)
	duration=forms.CharField(max_length=50)
	contact=forms.CharField()
	tel=forms.CharField()
	email=forms.EmailField()

prmonde/views.py
from django.core.mail import send_mail, BadHeaderError, EmailMultiAlternatives
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import render_to_string
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Article
from .forms import OrderForm

def home(request):
	articles = Article.objects.filter(date__lte=timezone.now()).order_by('-date')[:2]
	return render(request, 'prmonde/home.html', {'articles':articles})

def order(request):
	company='no company'
	product='no product'
	design=False
	duration='duration-none'
	contact='no contact'
	tel='123456'
	email='noemail@no.em'
	publicity_type='no_type'

	if request.method == 'POST' :
		form=OrderForm(request.POST)

		if form.is_valid():
			company=form.cleaned_data['company']
			product=form.cleaned_data['product']
			design=form.cleaned_data['design']
			duration=form.cleaned_data['duration']
			contact=form.cleaned_data['contact']
			tel=form.cleaned_data['tel']
			email=form.cleaned_data['email']
			publicity_type=form.cleaned_data['publicity_type']

			try:
				msg_plain = render_to_string('../templates/prmonde/email.txt', {'company':company,'product':product,'design':design,'duration':duration,'contact':contact,'tel':tel,'email':email, 'publicity_type':publicity_type})
				msg_html = render_to_string('../templates/prmonde/email.html', {'company':company,'product':product,'design':design,'duration':duration,'contact':contact,'tel':tel,'email':email, 'publicity_type':publicity_type})
				msg_plain_client = render_to_string('../templates/prmonde/email_client.txt')
				msg_html_client = render_to_string('../templates/prmonde/email_client.html')
				send_mail('New order',msg_plain,'PRMonde notification <prmondeagence@gmail.com>', ['prmondeagence@gmail.com'], html_message=msg_html)
				send_mail('PRMonde order',msg_plain_client,'PRMonde <prmondeagence@gmail.com>', [email], html_message=msg_html_client)
			except BadHeaderError:
				return HttpResponse('Invalid header found')
			return redirect('form_success')
	else:
		form=OrderForm()

	return render(request, 'prmonde/order.html', {})

def requirements(request):
    return render(request, 'prmonde/requirements.html', {})

def contact(request):
	return render(request, 'prmonde/contacts.html', {})

def form_success(request):
	return render(request, 'prmonde/order-success.html', {})

def articles(request):
	articles_list = Article.objects.filter(date__lte=timezone.now()).order_by('-date')
	page = request.GET.get('page')
	paginator = Paginator(articles_list, 10)

	try:
		articles = paginator.page(page)
	except PageNotAnInteger:
		articles = paginator.page(1)
	except EmptyPage:
		articles = paginator.page(paginator.num_pages)

	return render(request, 'prmonde/articles.html', {'articles' : articles})

def article_item(request, pk):
	article = get_object_or_404(Article, pk=pk)
	return render(request, 'prmonde/article-item.html', {'article':article})

prmonde/templates/prmonde/article-item.html
{% extends 'publicity_agency/index.html' %}
{% load staticfiles %}
{% block stylesheet %}
	<link rel="stylesheet" href="{% static 'css/articles.css' %}"/>
{% endblock stylesheet %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="com-md-12 col-sm-12 col-xs-12 text-left page-title">
			<div class="section-title article-title">
				<p>{{ article.title }}</p>
				<span></span>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<p class="article-item-preview">
				{{ article.preview }}
			</p>
			<div class="article-content">
				{{ article.content|safe }}
			</div>
		</div>
	</div>
	<div class="row source-row">
		<div class="col-md-6 col-sm-6 col-xs-6">
			<p class="article-date">{{ article.date|date:'j N o' }}</p>
		</div>
		<div class="col-md-6 col-sm-6 col-xs-6 text-right">
			<p class="article-source">
				<a href="{{ article.source }}" target="_blank">La source de l'article</a>
			</p>
		</div>
	</div>
</div>
{% endblock content %}
{% block scripts %}
	<script src="{% static 'js/article.js' %}"/></script>
{% endblock scripts %}

prmonde/templates/prmonde/articles.html
{% extends 'publicity_agency/index.html' %}
{% load staticfiles %}
{% block stylesheet %}
	<link rel="stylesheet" href="{% static 'css/articles.css' %}"/>
{% endblock stylesheet %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12 text-left page-title">
			<div class="section-title">
				<p>articles</p>
				<span></span>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<img class="section-img" src="{% static 'img/articles.jpg' %}" alt="">
		</div>
	</div>
</div>
<div class="container">
{% for article in articles %}
	<div class="row article-item">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<span class="date">{{ article.date|date:'j N o' }}</span>
			<a href="{% url 'article_item' pk=article.pk %}" class="article-link">{{ article.title }}</a>
			<p class="article-preview">{{ article.preview }}</p>
		</div>
	</div>
{% endfor %}
<div class="row">
	<div class="col-md-12 text-center">
		{% if articles.has_other_pages %}
		<ul class="pagination">
			{% if articles.has_previous %}
			<li><a href="?page={{ articles.previous_page_number }}">&laquo;</a></li>
			{% else %}
			<li class="disabled"><span>&laquo;</span></li>
			{% endif %}
			{% for i in articles.paginator.page_range %}
			{% if articles.number == i %}
			<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
			{% else %}
			<li><a href="?page={{ i }}">{{ i }}</a></li>
			{% endif %}
			{% endfor %}
			{% if articles.has_next %}
			<li><a href="?page={{ articles.next_page_number }}">&raquo;</a></li>
			{% else %}
			<li class="disabled"><span>&raquo;</span></li>
			{% endif %}
		</ul>
		{% endif %}
	</div>
</div>

</div>
{% endblock content %}

prmonde/templates/prmonde/contacts.html
{% extends 'publicity_agency/index.html' %}
{% load staticfiles %}
{% block stylesheet %}
	<link rel="stylesheet" href="{% static 'css/contacts.css' %}"/>
{% endblock stylesheet %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12 text-left page-title">
			<div class="section-title">
				<p>contacts</p>
				<span></span>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row contact-details-row">
		<div class="col-md-8 col-sm-8 col-xs-12">
			<p class="contact-details-title">Adresse</p>
			<p>25 Rue de Cléry, 75002 Paris, France</p>
			<p>Nous vous attendons chez nous <strong>lundi-vendredi de 9:00 à 18:00</strong></p>
		</div>
		<div class="col-md-4 col-sm-4 col-xs-12">
			<p class="contact-details-title">Téléphone</p>
			<a href="tel:+33 1 25 59 96 41" class="contacts-link"> +33 1 25 59 96 41</a>
			<p class="contact-details-title">Email</p>
			<a href="mailto:prmonde@gmail.com" class="contacts-link">prmonde@gmail.com</a>
		</div>
	</div>
	<div class="row map-row">
		<div class="col-md-12">
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2624.4707953367915!2d2.344645251412151!3d48.86830097918684!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66e17c81e85ed%3A0x8276f1ffc999a6cb!2s25+Rue+de+Cl%C3%A9ry%2C+75002+Paris%2C+France!5e0!3m2!1sen!2sua!4v1484848950571" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
		</div>
		
	</div>
</div>
<div class="container">
	<div class="row career-row">
		<div class="col-md-12">
			<div class="section-title career-title">
				<p>Carrière</p>
				<span></span>
			</div>
		</div>
		<div class="col-md-8">
			<p class="career-description">
				Nous sommes ouverts aux personnes talentueuses, enthousiastes et engagées qui sont capables de contribuer au développement de l'entreprise. Si vous êtes passionnés par des médias, design ou marketing, si vous voulez vous dévélopper dans une entreprise en plein croissance, n'hésitez pas nous <strong>envoyer votre CV</strong> à <a href="mailto:prmonde_recruit@gmail.com" class="contacts-link">prmonde_recruit@gmail.com</a>. Rejoins notre équipe!
			</p>
		</div>
		<div class="col-md-4">
			<img src="{% static 'img/career.jpeg' %}" alt="Career">
		</div>
	</div>
</div>

	
{% endblock content %}
{% block scripts %}
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
{% endblock scripts %}

prmonde/templates/prmonde/email.html
<table style="font-size: 16px;font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif;">
	<tbody>
		<tr>
			<td style="padding: 15px; margin: 0;">
				<p style="margin: 0; margin-bottom: 10px;">Bonjour,</p>
				<p style="margin: 0; margin-bottom: 10px;">Vous avez reçu une nouvelle commande.</p>
				<p style="font-size: 20px; text-align:center;"><strong>Détails</strong></p>
				<p><strong>Nom d'entreprise:</strong> {{company}}</p>
				<p><strong>Produit à promovoir:</strong> {{product}}</p>
				<p><strong>Type de publicité:</strong> {{publicity_type}}</p>
				<p><strong>Est-ce qu'il faul faire le design?</strong> {% if design %}Oui {% else %} Non{% endif %}</p>
				<p><strong>Durée de campagne de publicité:</strong> {{duration}}</p>
				<p style="font-size: 20px; text-align:center;"><strong>Contacts</strong></p>
				<p><strong>Personne à contacter:</strong> {{contact}}</p>
				<p><strong>Téléphone:</strong> {{tel}}</p>
				<p><strong>Email:</strong> {{email}}</p>
			</td>
		</tr>
	</tbody>
</table>

prmonde/templates/prmonde/email_client.html
<p>
	Bonjour,
</p>
<p>Merci pour votre commande. Notre manager vous contactera dans 20 minutes.</p>
<p>Si vous avez des questions, n'hésitez pas nous contacter par téléphone <span>+33 1 25 59 96 41</span> ou par email <span>prmonde@gmail.com</span></p>
<p>Cordialement,</p>
<p>PRMonde</p>

prmonde/templates/prmonde/home.html
{% extends 'publicity_agency/index.html' %}
{% load staticfiles %}
{% block stylesheet %}
	<link rel="stylesheet" href="{% static 'css/home.css' %}"/>
{% endblock stylesheet %}

{% block content %}
<section class="start-block">
	<div class="start-title">
		<p>PRMonde est une agence de communication créative unique. Créateurs de synergie, nous avons le talent pour regrouper efficacement les expertises afin de vous aider à vous démarquer.</p>
		<p class="arrow-more">
			<a href="#our-services">
				<i class="fa fa-angle-down" aria-hidden="true"></i>
			</a>
		</p>
	</div>
</section>
<section class="our-services" id="our-services">
	<div class="container">
		<div class="row">
			<div class="col-md-12 section-title">
				<p>nos services</p>
				<span></span>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4 col-sm-4 col-xs-12 text-center service-item">
				<img src="{% static 'img/design.png' %}" alt="Design graphique">
				<div class="service-description">
					<p>Design graphique</p>
					<p>Chaque expert en branding ou communication visuelle vous le dira: un design qui atteint ses objectifs est un design qui répond d’abord aux besoins des clients. C’est pourquoi chacun de nos designers prévoit un temps de recherche afin de cerner à la fois le profil de votre public cible, mais aussi leurs comportements, que ce soit en ligne ou dans leur consommation de médias traditionnels.</p>
				</div>
			</div>
			<div class="col-md-4 col-sm-4 col-xs-12 text-center service-item">
				<img src="{% static 'img/transport.png' %}" alt="Publicité dans le transport">
				<div class="service-description">
					<p>Publicité dans le transport</p>
					<p>Aujourd’hui, les cibles les plus stratégiques de la publicité sont les individus les plus mobiles. Pour les toucher, il faut être présent là où ils sont réceptifs et disponibles, directement sur leurs lieux de mobilité : les métros et les bus, des services en ajustement constant avec les transformations des pôles urbains, et les gares, qui bénéficient de situations privilégiées dans l’espace urbain.</p>
				</div>
			</div>
			<div class="col-md-4 col-sm-4 col-xs-12 text-center service-item">
				<img src="{% static 'img/presse.png' %}" alt="Campagne presse">
				<div class="service-description">
					<p>Campagne presse</p>
					<p>Les relations presse offrent un cadre d’expression privilégié et flexible pour une entreprise qui souhaite mettre en scène ses produits, travailler son image, communiquer sur ses valeurs, asseoir sa notoriété, se bâtir une réputation ou la défaire …</p>
				</div>
			</div>
		</div>
	</div>
</section>
<section class="about-us">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-6 col-sm-12">
				<div class="about">
					<div class="section-title">
						<p>qui sommes nous</p>
						<span></span>
					</div>
					<div class="about-description">
					<p><strong>PRMonde</strong> est une agence de communication d’abord et avant tout qui a su adapter son offre au fil des années. C’est une agence marketing, de publicité, une firme-conseil en stratégie 360. Une agence totale. C’est une équipe créative, génératrice d’idées, passionnée de la vidéo et génie de l’informatique. En mode recherche et développement depuis 2007, l’équipe de PRMonde développe des solutions originales et innovatrices pour surpasser les objectifs de nos clients.</p> 
						<p>
							<strong>Notre mission</strong> est de créer de la synergie entre les marques et les gens en utilisant tous les canaux de communication mis à notre disposition.
						</p>
						<p>
							Notre seule <strong>priorité est le public</strong>. Alors, nous proposons des idées intelligentes et sensibles.
						</p>
						<p> Une marque c’est <strong>un style</strong>. Et pas le nôtre. Alors, nos campagnes sont très spécifiques aux entreprises pour lesquelles nous travaillons et donc très différentes les unes des autres.
						</p>
					</div>
				</div>
				
			</div>
			<div class="col-md-6  col-sm-12 about-img"> 
			</div>
		</div>
	</div>
</section>
<section class="statistic">
	<div class="container">
		<div class="row">
			<div class="statistic-item text-center">
				<span class="statictic-number">10</span>
				<p>ans de travail</p>
			</div>
			<span class="border"></span>
			<div class="statistic-item text-center">
				<span class="statictic-number">40</span>
				<p>spécialistes créatifs</p>
			</div>
			<span class="border"></span>
			<div class="statistic-item text-center">
				<div>
					<span class="statictic-number">4</span>
					<p>succursales dans le monde</p>
				</div>
			</div>
			<span class="border"></span>
			<div class="statistic-item text-center">
				<span class="statictic-number">230+</span>
				<p>clients satisfaits</p>
			</div>
		</div>
	</div>
</section>
<section class="articles">
	<div class="container">
		<div class="row">
			<div class="col-md-12 section-title">
				<p>articles</p>
				<span></span>
			</div>
		</div>
		{% for article in articles %}
		<div class="row article-item">
			<div class="col-md-12 col-sm-12">
				<span class="date">{{ article.date|date:'j N o' }}</span>
				<a href="{% url 'article_item' pk=article.pk %}" class="article-link">{{ article.title }}</a>
				<p class="article-preview">{{ article.preview }}</p>
			</div>
		</div>
		{% endfor %}
		<p class="text-center">
			<a class="btn-standart" href="{% url 'articles'%}">Lire tous les articles</a>
		</p>
	</div>
</section>
<div class="clear"></div>
{% endblock content %}
{% block scripts %}
	<script src="{% static 'js/home.js' %}"/></script>
{% endblock scripts %}

prmonde/templates/prmonde/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>PRMonde</title>
	<link rel="stylesheet" href="{% static 'libs/bootstrap/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'libs/bootstrap/bootstrap-theme.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'libs/font-awesome/css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/main.css' %}"/>
	{% block stylesheet %}
	{% endblock %}
</head>
<body>
	<div class="wrapper">
		<header>
			<nav class="navbar navbar-default navbar-fixed navbar-menu" role="navigation">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'img/logo.png' %}" alt="Métrolicité"></a>
					</div>
					<div class="collapse navbar-collapse navbar-menu" id="navbar">
						<ul class="nav navbar-nav navbar-right">
							<li class="{% if request.resolver_match.url_name == "home" %}active{% endif %}"><a href="{% url 'home' %}">Accueil</a></li>
							<li class="{% if request.resolver_match.url_name == "articles" %}active{% endif %}"><a href="{% url 'articles' %}">Articles</a></li>
							<li class="{% if request.resolver_match.url_name == "order" %}active{% endif %}"><a href="{% url 'order' %}">Reservation</a></li>
							<li class="{% if request.resolver_match.url_name == "contact" %}active{% endif %}"><a href="{% url 'contact' %}">Contacts</a></li>
						</ul>
					</div>
				</div>
			</nav>		
		</header>
		<div class="content">
				{% block content %}
				{% endblock %}
		</div>
		<footer>
			<div class="container">
				<div class="row">
					<div class="col-md-6 col-sm-6">
					<p class="contacts-title">contacts</p>
					<p>25 Rue de Cléry <br>
						75002 Paris, France<br>
						+33 1 25 59 96 41</p>
					<p class="networks-links-mob">
						<span><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></span>
						<span><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></span>
						<span><a href="#"><i class="fa fa-youtube" aria-hidden="true"></i></a></span>
						<span><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></span>
					</p>
					</div>
					<div class="col-md-6 col-sm-6">
					<p class="networks-links text-center">
						<span><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></span>
						<span><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></span>
						<span><a href="#"><i class="fa fa-youtube" aria-hidden="true"></i></a></span>
						<span><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></span>
					</p>
					</div>
				</div>
			</div>			
		</footer>
	</div>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script src="{% static 'libs/bootstrap/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
	{% block scripts %}
	{% endblock %}
</body>
</html>

prmonde/templates/prmonde/order-success.html
{% extends 'publicity_agency/index.html' %}
{% load staticfiles %}
{% block stylesheet %}
	<link rel="stylesheet" href="{% static 'css/order.css' %}"/>
{% endblock stylesheet %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<div class="order-confirmation">
					<i class="fa fa-check" aria-hidden="true"></i>
					<p>Merci, votre commande a été accepté. Dans 15 minutes notre manager vous contactera.</p>
				</div>
				<p class="text-center back-homepage"><a href="{% url 'home'%}">Retour à la page d'accueil </a></p>
			</div>
		</div>
	</div>
{% endblock content %}

prmonde/templates/prmonde/order.html
{% extends 'publicity_agency/index.html' %}
{% load staticfiles %}
{% block stylesheet %}
	<link rel="stylesheet" href="{% static 'css/order.css' %}"/>
{% endblock stylesheet %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12 text-left page-title">
			<div class="section-title">
				<p>faire commande</p>
				<span></span>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="order-invitation">
				<p >Ici vous pouvez faire une commande pour la publicité de votre produits. C'est trés simple et vite. Il faut seulement remplir le formulaire ci-dessous et nous vous contacterons dans <strong>15 minutes</strong>. Tous les champs dans le formulaires sont obligatoires. Nous avons besoins de cette information avec le but de trouver le manager avec des compétences nécessaires</p>
				<p>
					Aussi vous pouvez télécharger la 
					<a href="{% static 'doc/price_list.pdf'%}" class="link-download" target="_blank">list de prix </a>
					et les 
					<a href="{% static 'doc/tech.pdf'%}" class="link-download" target="_blank">exigences techniques </a>
					aux matériaux pour la publicité dans le transport.
				</p>
				<p>
					Si vous avez des questions n'hésitez pas nous contacter par téléphone
					<a href="tel:+33 1 25 59 96 41"> +33 1 25 59 96 41</a> ou par email <a href="mailto:prmonde@gmail.com">prmonde@gmail.com</a>
				</p>
			</div>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<form name = "form" action = "{% url 'order' %}" method = "POST" class="order-form" id="order-form">
				{% csrf_token %}
				<p class="form-title">Commande</p>
				<div class="form-item">
					<label for="id_company">Nom d'entreprise:</label>
					<input id="id_company" class="check-item" maxlength="100" name="company" type="text" >
				</div>
				<div class="form-item">
					<label for="id_product">Produit à promouvoir:</label>
					<input id="id_product" class="check-item" maxlength="200" name="product" type="text" >
				</div>
				<div class="form-item">
					<span><strong>Type de publicité:</strong></span> 
					<label for="id_publicity_type_0" class="label-radio">
						<input id="id_publicity_type_0" name="publicity_type" type="radio" value="transport" checked> 
						dans le transport
					</label>
					<label for="id_publicity_type_1" class="label-radio">
						<input id="id_publicity_type_1" name="publicity_type" type="radio" value="presse" > 
						campagne presses
					</label>
				</div>
				<div class="form-item-design">
					<span><strong>Avez-vous besoin du design?</strong></span>
					<label for="id_design" class="label-radio">
					<input id="id_design" name="design" type="checkbox">
					Oui</label>
				</div>
				<div class="form-item">
					<label for="id_duration">La durée de campagne de publicité:</label>
					<input id="id_duration" maxlength="50" class="check-item" name="duration" type="text"  placeholder="2 semaines, 1 mois etc">
				</div>
				<p class="form-subtitle">Contacts</p>
				<div class="form-item">
					<label for="id_contact">Personne à contacter: </label>
					<input id="id_contact" name="contact" class="check-item" type="text" >
				</div>
				<div class="form-item">
					<label for="id_tel">Téléphone: </label>
					<input id="id_tel" name="tel" class="check-item" type="text" >
				</div>
				<div class="form-item">
					<label for="id_email">Email:</label>
					<input id="id_email" name="email" class="check-item" type="email" >
				</div>
				<p class="text-center">
					<button type="submit" class="btn-standart">Envoyer</button>
				</p>
				
			</form>
		</div>
	</div>
</div>
{% endblock content %}
{% block scripts %}
<script src="{% static 'js/order.js' %}"></script>
{% endblock %}

prmonde/templates/prmonde/requirements.html
{% extends 'publicity_agency/index.html' %}
{% block content %}
	<!-- Here write your code -->
	<p><i class="fa fa-key" aria-hidden="true"></i> Technical requirements</p>
{% endblock content %}